name: Deploy Finance API (MonsterASP)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/Finance.Api/Finance.Api.csproj

      - name: Build
        run: dotnet build src/Finance.Api/Finance.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/Finance.Api/Finance.Api.csproj -c Release -o publish

      - name: Deploy to Monster
        shell: pwsh
        env:
          WEBDEPLOY_PUBLISH_URL: ${{ secrets.WEBDEPLOY_PUBLISH_URL }}
          WEBDEPLOY_SITE: ${{ secrets.WEBDEPLOY_SITE }}
          WEBDEPLOY_USERNAME: ${{ secrets.WEBDEPLOY_USERNAME }}
          WEBDEPLOY_PASSWORD: ${{ secrets.WEBDEPLOY_PASSWORD }}
        run: |
          $msdeploy = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"

          $computerName = "https://$env:WEBDEPLOY_PUBLISH_URL`:8172/msdeploy.axd?site=$env:WEBDEPLOY_SITE"

          & $msdeploy `
            -verb:sync `
            -source:contentPath="publish" `
            -dest:contentPath="$env:WEBDEPLOY_SITE",computerName="$computerName",userName="$env:WEBDEPLOY_USERNAME",password="$env:WEBDEPLOY_PASSWORD",authType="Basic" `
            -allowUntrusted `
            -enableRule:AppOffline
