name: Deploy Finance API (MonsterASP)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/Finance.Api/Finance.Api.csproj

      - name: Build
        run: dotnet build src/Finance.Api/Finance.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/Finance.Api/Finance.Api.csproj -c Release -o publish

      - name: Deploy to MonsterASP
        shell: pwsh
        env:
          WEBDEPLOY_PUBLISH_URL: ${{ secrets.WEBDEPLOY_PUBLISH_URL }}
          WEBDEPLOY_SITE: ${{ secrets.WEBDEPLOY_SITE }}
          WEBDEPLOY_USERNAME: ${{ secrets.WEBDEPLOY_USERNAME }}
          WEBDEPLOY_PASSWORD: ${{ secrets.WEBDEPLOY_PASSWORD }}
        run: |

          Write-Host "Starting deployment..."

          $msdeploy = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"

          if (!(Test-Path $msdeploy)) {
              Write-Error "msdeploy not found"
              exit 1
          }

          $publishPath = (Resolve-Path "publish").Path

          $computerName = "https://$env:WEBDEPLOY_PUBLISH_URL`:8172/msdeploy.axd"

          $dest = "iisApp=$env:WEBDEPLOY_SITE,computerName=$computerName,userName=$env:WEBDEPLOY_USERNAME,password=$env:WEBDEPLOY_PASSWORD,authType=Basic"

          Write-Host "Publish folder: $publishPath"
          Write-Host "Deploying to: $env:WEBDEPLOY_SITE"

          & $msdeploy `
            -verb:sync `
            -source
